2025-06-24 09:18:51,413 - INFO - Starting run 1/1
2025-06-24 09:19:16,369 - ERROR - Run 1 failed due to: index 177 is out of bounds for axis 0 with size 165
Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/test_generated_algorithm.py", line 220, in run_optimization
    best_solution, best_fitness, _ = optimizer.optimize(
                                     ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/test_generated_algorithm.py", line 75, in optimize
    offspring = self.generate_offspring(objective_function)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/test_generated_algorithm.py", line 126, in generate_offspring
    mutant = self.population[i] + self.F * (pbest - self.population[i] + self.population[a] - self.population[b])
                                                                                              ~~~~~~~~~~~~~~~^^^
IndexError: index 177 is out of bounds for axis 0 with size 165
2025-06-24 09:19:16,380 - INFO - Starting run 1/1
2025-06-24 09:20:20,251 - ERROR - Run 1 failed due to: index 169 is out of bounds for axis 0 with size 165
Traceback (most recent call last):
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/test_generated_algorithm.py", line 220, in run_optimization
    best_solution, best_fitness, _ = optimizer.optimize(
                                     ^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/test_generated_algorithm.py", line 75, in optimize
    offspring = self.generate_offspring(objective_function)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macbook/Documents/Code/LLMdesignedEA-comp/test_generated_algorithm.py", line 126, in generate_offspring
    mutant = self.population[i] + self.F * (pbest - self.population[i] + self.population[a] - self.population[b])
                                                                                              ~~~~~~~~~~~~~~~^^^
IndexError: index 169 is out of bounds for axis 0 with size 165
